COMMANDS_SEPARATOR = "$"
DIRECTORY_SYMBOL = "dir"
PARENT_DIRECTORY_SYMBOL = ".."
ROOT_DIRECTORY_SYMBOL = "/"
CHANGE_DIRECTORY_COMMAND = "cd"
LIST_CONTENTS_COMMAND = "ls"
SMALL_DIRECTORY_SIZE_THRESHOLD = 100_000
