"""Various constants used for Rock Paper Scissors shapes and other data about them."""


ROCK = "X"
PAPER = "Y"
SCISSORS = "Z"
OPPONENT_ROCK = "A"
OPPONENT_PAPER = "B"
OPPONENT_SCISSORS = "C"

IDENTICAL_SHAPES = {
    OPPONENT_ROCK: ROCK,
    OPPONENT_PAPER: PAPER,
    OPPONENT_SCISSORS: SCISSORS,
}

WINNING_MOVES = {
    ROCK: SCISSORS,
    PAPER: ROCK,
    SCISSORS: PAPER,
}
LOSING_MOVES = {
    ROCK: PAPER,
    PAPER: SCISSORS,
    SCISSORS: ROCK,
}


SHAPE_TO_SCORE = {OUR_ROCK: 1, OUR_PAPER: 2, OUR_SCISSORS: 3}
