"""Various constants used for Rock Paper Scissors shapes and other data about them."""


ROCK = "X"
PAPER = "Y"
SCISSORS = "Z"
OPPONENT_ROCK = "A"
OPPONENT_PAPER = "B"
OPPONENT_SCISSORS = "C"

IDENTICAL_SHAPES = {
    OPPONENT_ROCK: ROCK,
    OPPONENT_PAPER: PAPER,
    OPPONENT_SCISSORS: SCISSORS,
}

OUR_TO_OPPONENT_SHAPE_DEFEAT = {
    OUR_ROCK: OPPONENT_SCISSORS,
    OUR_PAPER: OPPONENT_ROCK,
    OUR_SCISSORS: OPPONENT_PAPER,
}

OPPONENT_TO_OUR_SHAPE_DEFEAT = {
    OPPONENT_ROCK: OUR_SCISSORS,
    OPPONENT_PAPER: OUR_ROCK,
    OPPONENT_SCISSORS: OUR_PAPER,
}


SHAPE_TO_SCORE = {OUR_ROCK: 1, OUR_PAPER: 2, OUR_SCISSORS: 3}
